require("cammarb.plugins_config.lsp")
require("cammarb.plugins_config.mason")
require("cammarb.plugins_config.nvim-tree")
require("cammarb.plugins_config.telescope")
require("cammarb.plugins_config.treesitter")